
name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: yarn install, build
      run: |
        yarn
        yarn docs:build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.BLOG_SECRET}}
        BRANCH: main
        FOLDER: docs-dist
        REPOSITORY_NAME: kangchangyuan/kangchangyuan.github.io
        # TARGET_FOLDER: blog

      env:
        CI: true
